name: Build Frozen Bubble APK

on:
  push:
    branches: [ "android_studio" ]
  pull_request:
    branches: [ "android_studio" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Install Android NDK via SDKManager
      run: echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;27.0.12077973"

    - name: Configure SDK and NDK paths
      run: echo "sdk.dir=$ANDROID_HOME" > local.properties; echo "ndk.dir=$ANDROID_HOME/ndk/27.0.12077973" >> local.properties

    - name: Patch Windows ndk-build references for Linux Runner
      run: find . -name "build.gradle" -exec sed -i 's/ndk-build.cmd/ndk-build/g' {} +

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug -x lint -x lintVitalRelease
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: frozenbubble/build/outputs/apk/debug/*.apk # Path to output file
